# Why to Use  Numpy?


*NumPy provides efficient storage*

*It also provides better ways of handling data for processing*

*It is fast*

*It is easy to learn*

*NumPy uses relatively less memory to store data*

# Jupyter Notebook


*It is an open source web application that allows you to create and share documents that contain live code, equations, visualisations and narrative text*

*The notebook has support for over 40 programming languages, including Python, R, Julia and Scala*

*Notebooks can be shared with others using email, Dropbox, GitHub and the Jupyter Notebook Viewer*

*Your code can produce rich, interactive output : HTML, images, LaTeX, and custom MIME types*


In [1]:
import numpy as np

In [2]:
myarr = np.array([3,6,77,7], np.int8)

In [3]:
myarr

array([ 3,  6, 77,  7], dtype=int8)

In [4]:
myarr[0]

3

In [5]:
myarr.shape

(4,)

In [6]:
myarr=np.array([[3,6,77,7]], np.int8)

In [7]:
myarr[0,1]

6

In [8]:
myarr.shape

(1, 4)

In [9]:
myarr.dtype

dtype('int8')

*Overwriting the elements*

In [10]:
myarr[0,1] = 45

In [11]:
myarr

array([[ 3, 45, 77,  7]], dtype=int8)

# Array creation: Conversion from other Python Structures

*lists*

In [12]:
listarray = np.array([[1,2,3], [5,8,5], [0,3,1]])

In [13]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [14]:
listarray.shape

(3, 3)

In [15]:
listarray.dtype

dtype('int64')

In [16]:
listarray.size

9

In [17]:
listarray[0][2] = 4
listarray

array([[1, 2, 4],
       [5, 8, 5],
       [0, 3, 1]])

*tuples*

In [18]:
np.array({34,23,23})

array({34, 23}, dtype=object)

# Intrinsic numpy array creation objects (eg, arange, ones, zeros, etc)

In [19]:
zeros = np.zeros((2,5))

In [20]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

*arange - range of numbers*

In [21]:
rng = np.arange(15)

In [22]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

*linspace - intial number to final number but with the last declared number of real numbers in between them*

In [23]:
lspace = np.linspace(1,6,12)

In [24]:
lspace

array([1.        , 1.45454545, 1.90909091, 2.36363636, 2.81818182,
       3.27272727, 3.72727273, 4.18181818, 4.63636364, 5.09090909,
       5.54545455, 6.        ])

*empty - an empty array filled with random values in which we can assign the values later on*

In [25]:
emp = np.empty((4,6))

In [26]:
emp

array([[0.00000000e+000, 2.21026219e-314, 0.00000000e+000,
        5.21501891e-310, 4.94065646e-324, 0.00000000e+000],
       [0.00000000e+000, 4.04738577e-320, 0.00000000e+000,
        1.23022346e-321, 6.94574234e-310, 9.88131292e-324],
       [0.00000000e+000, 0.00000000e+000, 6.94576866e-310,
        3.06320700e-322, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        4.94065646e-324,             nan, 0.00000000e+000]])

*empty_like - creates an empty array using the size of already predefined array. The values here will be visible as those of the predefined array but there is nothing. We need to assign the values later on*

In [27]:
emp_like = np.empty_like(lspace)

In [28]:
emp_like

array([1.        , 1.45454545, 1.90909091, 2.36363636, 2.81818182,
       3.27272727, 3.72727273, 4.18181818, 4.63636364, 5.09090909,
       5.54545455, 6.        ])

*identity - identity matrix*

In [29]:
ide = np.identity(45)

In [30]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

***Functions***

In [31]:
arr = np.arange(99)

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

tolist() - converts the numpy array into a list

In [33]:
arr.tolist()

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98]

reshaping the array - reshape(a,b) - breaking the matrix into *a* parts with *b* elements in each part

In [34]:
arr = arr.reshape(3,33)

In [35]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

ravel - becomes a 1D array

In [36]:
arr = arr.ravel()

In [37]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

# NumPy Axis

*The axes of the matrices*

*In case of multi dimensional matrices, the axis0 stands for vertical and the axis1 for horizontal etc*

In [38]:
x = [[1,2,3], [4,5,6], [7,1,0]]

In [39]:
ar = np.array(x)

In [40]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [41]:
ar.sum(axis=0)

array([12,  8,  9])

In [42]:
ar.sum(axis=1)

array([ 6, 15,  8])

T - transpose

In [43]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

flat - iterator

In [44]:
ar.flat

In [45]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


ndim - no.of dimensions

In [46]:
ar.ndim

2

size - no.of elements

In [47]:
ar.size

9

nbytes - total bytes consumed

In [48]:
ar.nbytes

72

***In 1D***

**argmax() function**
*gives the index of the max element*

**argmin() function**
*gives the index of the min element*

**argsort() function**
*gives the indices if the array is sorted*

In [49]:
one = np.array([1,3,4,634,2])

In [50]:
one.argmax()

3

In [51]:
one.argmin()

0

In [52]:
one.argsort()

array([0, 4, 1, 2, 3])

the same for 2D

In [53]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [54]:
ar.argmax()

6

In [55]:
ar.argmin()

8

In [56]:
ar.argmax(axis=0)

array([2, 1, 1])

In [57]:
ar.argmin(axis=1)

array([0, 0, 2])

In [58]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [59]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]])

In [60]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [61]:
ar.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

# More applications on matrices

*addition of two matrices*

In [62]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [63]:
ar2 = np.array([[1,2,1],
[4,0,6],
[8,1,0]])

In [64]:
ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

but we can see that this can't be done in case of direct lists

In [65]:
[2,3] + [4,5]

[2, 3, 4, 5]

*multiplication of arrays elements' wise*

In [66]:
ar * ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

*square root*

In [67]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

*sum, max, min*

In [68]:
ar.sum()

29

In [69]:
ar.min()

0

In [70]:
ar.max()

7

*where - returns a tuple of array*

In [71]:
a = np.where(ar > 5)

In [72]:
a

(array([1, 2]), array([2, 0]))

In [73]:
type(a)

tuple

count_nonzero - no.of non zero elements

In [74]:
np.count_nonzero(ar)

8

nonzero gives the tuples of the indices for all the dimensions wherever the element is non-zero

In [75]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))

In [76]:
ar[1,2] = 0

In [77]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 0, 1]))

# Checking that NumPy uses less storage

In [78]:
import sys

In [79]:
py_ar = [0, 4, 55, 2]

In [80]:
np_ar = np.array(py_ar)

In [81]:
sys.getsizeof(1)*len(py_ar)

112

In [82]:
np_ar.itemsize * np_ar.size

32